@echo off
setlocal
cd /d "%~dp0"

set FXC=
where fxc >nul 2>nul && set FXC=fxc
if not defined FXC for /f "delims=" %%d in ('dir /b /ad /o-n "%ProgramFiles(x86)%\Windows Kits\10\bin\10.*"') do (
    if not defined FXC if exist "%ProgramFiles(x86)%\Windows Kits\10\bin\%%d\x86\fxc.exe" set "FXC=%ProgramFiles(x86)%\Windows Kits\10\bin\%%d\x86\fxc.exe"
)
if not defined FXC (
    echo fxc.exe not found: run from a Visual Studio developer prompt or install the Windows SDK
    exit /b 1
)

set OUT=..\..\src\features\smaa_shaders.h

call :compile vs_3_0 DX9_SMAAEdgeDetectionVS             SmaaVS0 || exit /b 1
call :compile ps_3_0 DX9_SMAALumaEdgeDetectionPS         SmaaPS0 || exit /b 1
call :compile vs_3_0 DX9_SMAABlendingWeightCalculationVS SmaaVS1 || exit /b 1
call :compile ps_3_0 DX9_SMAABlendingWeightCalculationPS SmaaPS1 || exit /b 1
call :compile vs_3_0 DX9_SMAANeighborhoodBlendingVS      SmaaVS2 || exit /b 1
call :compile ps_3_0 DX9_SMAANeighborhoodBlendingPS      SmaaPS2 || exit /b 1

(
    echo #pragma once
    echo.
    echo // Generated by tools\smaa\compile.bat from SMAA.hlsl - do not edit
    echo.
    type SmaaVS0.tmp SmaaPS0.tmp SmaaVS1.tmp SmaaPS1.tmp SmaaVS2.tmp SmaaPS2.tmp
) > "%OUT%"
del *.tmp
echo Wrote %OUT%
exit /b 0

:compile
"%FXC%" /nologo /T %1 /E %2 /O3 /Fh %3.tmp /Vn %3 SMAA.hlsl
exit /b %errorlevel%
